// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package assets_and_maintenance.actions;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Java_action_Yearly extends CustomJavaAction<java.lang.Void>
{
	private java.util.Date StartDate;
	private java.util.Date EndDate;
	private java.util.Date SpecificDate;
	private java.util.List<IMendixObject> __DateList;
	private java.util.List<assets_and_maintenance.proxies.PreventiveSchedule> DateList;

	public Java_action_Yearly(IContext context, java.util.Date StartDate, java.util.Date EndDate, java.util.Date SpecificDate, java.util.List<IMendixObject> DateList)
	{
		super(context);
		this.StartDate = StartDate;
		this.EndDate = EndDate;
		this.SpecificDate = SpecificDate;
		this.__DateList = DateList;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		this.DateList = new java.util.ArrayList<assets_and_maintenance.proxies.PreventiveSchedule>();
		if (__DateList != null)
			for (IMendixObject __DateListElement : __DateList)
				this.DateList.add(assets_and_maintenance.proxies.PreventiveSchedule.initialize(getContext(), __DateListElement));

		// BEGIN USER CODE
		Calendar specificDate = Calendar.getInstance();
		Calendar startDate = Calendar.getInstance();
		Calendar endDate = Calendar.getInstance();
		specificDate.setTime(SpecificDate);
		startDate.setTime(StartDate);
		endDate.setTime(EndDate);
		int date = specificDate.get(Calendar.DAY_OF_MONTH);
		Date sdate = startDate.getTime();
		Date edate = endDate.getTime();
List<Date> generatedDate = getYearlyDates(SpecificDate,sdate,edate);
		
		for(int i=0;i<DateList.size();i++) {
			DateList.get(i).setDate(generatedDate.get(i));
		}
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Java_action_Yearly";
	}

	// BEGIN EXTRA CODE
	public List<Date> getYearlyDates(Date date,Date startdate, Date enddate ) {
		List<Date> dates = new ArrayList<Date>();
		 Calendar start = Calendar.getInstance();//start
			Calendar spec = Calendar.getInstance();
			Calendar end = Calendar.getInstance();
			start.setTime(startdate);
			spec.setTime(date);
			end.setTime(enddate);
			int max=15;
			Date startDate = start.getTime();
			
			Date endDate = end.getTime();
			for(int i=0;i<15;i++){
			    Date specDate = spec.getTime();
			    if(specDate.after(startDate) && specDate.before(endDate)){
			        dates.add(specDate);
			        spec.add(Calendar.MONTH,12);
			    }
			    else if(specDate.before(startDate)){
			        spec.add(Calendar.MONTH,12);
			        dates.add(spec.getTime());
			    }
			    
			}
		return dates;
	}
	// END EXTRA CODE
}
