// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package assets_and_maintenance.actions;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Java_action_Daily extends CustomJavaAction<java.lang.Void>
{
	private java.util.Date StartDate;
	private java.util.Date EndDate;
	private java.util.List<IMendixObject> __DateList;
	private java.util.List<assets_and_maintenance.proxies.PreventiveSchedule> DateList;

	public Java_action_Daily(IContext context, java.util.Date StartDate, java.util.Date EndDate, java.util.List<IMendixObject> DateList)
	{
		super(context);
		this.StartDate = StartDate;
		this.EndDate = EndDate;
		this.__DateList = DateList;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		this.DateList = new java.util.ArrayList<assets_and_maintenance.proxies.PreventiveSchedule>();
		if (__DateList != null)
			for (IMendixObject __DateListElement : __DateList)
				this.DateList.add(assets_and_maintenance.proxies.PreventiveSchedule.initialize(getContext(), __DateListElement));

		// BEGIN USER CODE
		Calendar start = Calendar.getInstance();
		Calendar end = Calendar.getInstance();
		start.setTime(StartDate);
		end.setTime(EndDate);
		Date sdate = start.getTime();
		Date edate = end.getTime();
		List<Date> generatedDate = getDates(sdate,edate);
		for(int i=0;i<DateList.size();i++) {
			DateList.get(i).setDate(generatedDate.get(i));
		}
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Java_action_Daily";
	}

	// BEGIN EXTRA CODE
	public List<Date> getDates(Date startdate, Date enddate ) {
		List<Date> dates = new ArrayList<Date>();
		 Calendar start = Calendar.getInstance();//start
			Calendar end = Calendar.getInstance();
			Calendar spec = Calendar.getInstance();
			start.setTime(startdate);
			end.setTime(enddate);
			spec.setTime(startdate);
			while(spec.before(end) || spec.equals(end)) {
				if(spec.before(end) || spec.equals(end)){ 
	        		dates.add(spec.getTime());
	            	spec.add(Calendar.DAY_OF_MONTH,1);
	        	}
			}
			return dates;	
	}
	// END EXTRA CODE
}
